### ISSUE TITLE
Crash when choose `pikachu-world-cap`

### ISSUE THREAD

**Issue by haunt98** [talwat/pokeget-rs#13]
After upgarde to version `v1.6.2`

I got crash when run `pokeget pikachu-world-cap`

```
thread 'main' panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/pokeget-1.6.2/src/list.rs:71:24:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by talwat** [comment]
I implemented a new List system, which properly formatted names but also took away from some of the flexibility of pokeget. I'll work on making that sort of input work, but for now you can try `pokeget pikachu --form world-cap`.

**Comment by talwat** [comment]
Fixed with [this commit](https://github.com/talwat/pokeget-rs/commit/f09dc802549f8690bef6073b8a4721e7c76a463f), v1.6.3 will be published to the AUR later today. Thanks :)
