### ISSUE TITLE
check for 0

### ISSUE THREAD

**Issue by TheCrazyGM** [talwat/pokeget-rs#2]
If `pokeget 0` is run, it will panic, probably should add a check for that.

```
thread 'main' panicked at 'index out of bounds: the len is 905 but the index is 18446744073709551615', src/sprites.rs:23:33
```

**Comment by talwat** [comment]
Yeah that's a good idea. Should I redirect it to bulbasaur or a random pokemon or just put an error message?

**Comment by TheCrazyGM** [comment]
I personally would have it print a message to enter a valid Pokedex id.

On that same note, I'd check the upper end too, `pokeget 10000000` also
panicked.

**Comment by talwat** [comment]
I decided to just redirect it to a random pokemon, but for the high one I think it should say the same "pokemon not found" error as you get from `pokeget doesnotexist`.

**Comment by TheCrazyGM** [comment]
That makes sense. Would be better than having to adjust the upper check
when new ones get added to the sprites in the future.
