### ISSUE TITLE
(Minor Complaint) Name of pokemon displayed before sprite.

### ISSUE THREAD

**Issue by droshux** [talwat/pokeget-rs#3]
I am using your (very cool) code to show a little picture of my favourite pokemon at the top of every new terminal window and it's working great! However the name of the pokemon was on top of the sprite and it was mildly annoying. What would be ideal would be if that didn't happen, or it was possible to turn off but like the title says this is a super tiny complaint and so you don't need to bother fixing it. :) :)

By the way: this tool is super cool, thanks for making it!

Here's the workaround I used:
```bash
pokeget umbreon > /tmp/umbreonTEMP.txt
clear
cat /tmp/umbreonTEMP.txt
rm /tmp/umbreonTEMP.txt
```
Piping to `sed` (or anything else similar) won't work here because the name of the pokemon gets written to a different stream.

**Comment by talwat** [comment]
Hmm, that's a super easy fix, I'm a bit of a dunce for not noticing it earlier. Thanks!

**Comment by talwat** [comment]
It's actually fixed on my end with pokeget 1.2.4. What version are you using? (`pokeget --version`)

**Comment by droshux** [comment]
I'm also using 1.2.4 but the issue still appears...
![Image of bug](https://github.com/talwat/pokeget-rs/assets/71277314/de2e6d87-0b15-45d5-9389-15768734ce74)

**Comment by talwat** [comment]
Oh, I misunderstood what you meant. You could try and get it so that you filter out stderr, but I could also make a flag to disable the name. I'll go ahead and do the latter now.

**Comment by talwat** [comment]
Publishing now...

**Comment by droshux** [comment]
That's fantastic thank's for the rapid fix :) :)
Genuinely appreciate it!

**Comment by talwat** [comment]
Not a problem :)

Sorry for the misunderstanding earlier.
