### ISSUE TITLE
Request to add Neofetch sysinfo

### ISSUE THREAD

**Issue by Sarthak950** [talwat/pokeget-rs#4]

**Comment by talwat** [comment]
That's a bit vague, do you mean instructions on how to use it with neofetch?

**Comment by Sarthak950** [comment]
yes if it is available or a feature request if not

**Comment by dustin4242** [comment]
I don't believe there is a way to do this with neofetch specifically however you can use a seperate command that can put the two together called bfetch: [bfetch](https://github.com/NNBnh/bfetch)
I used this in the past with pokeget when I wanted the system information next to the pokemon

**Comment by dustin4242** [comment]
If we wanted this in pokeget I guess try to put the output of neofetch next to the logo when pokeget is run with an argument possibly

**Comment by talwat** [comment]
Yeah, I tried putting the output of pokeget into a file and then pointing neofetch to it with `--ascii`, but it didn't really work. My guess is something to do with length calculations. Anyhow, it's more of a limitation in neofetch, but there are probably some other programs that fix this bug.

**Comment by CactiChameleon9** [comment]
```
_pokemon="$(pokeget 0 --hide-name)"
fastfetch --data-raw "$_pokemon"
```
that worked for me with fastfetch

**Comment by Sarthak950** [comment]
i think i will build it my self

**Comment by cyborgdennett** [comment]
any way to do it with multiple pokemon?

**Comment by cyborgdennett** [comment]
![image](https://github.com/talwat/pokeget-rs/assets/40475862/7114d984-7a2d-43a1-b407-a252d11c880f)
You might enjoy this one

**Comment by cyborgdennett** [comment]
Found a much better command for this
```
( pokeget 1 2 --hide-name; pokeget 2 1 --hide-name) | cat | fastfetch --file-raw -
```
![image](https://github.com/talwat/pokeget-rs/assets/40475862/a7d0c680-346c-4e9a-b88f-ed6b63f632de)

**Comment by Sarthak950** [comment]
thanks man 
```bash
    pokeget random --hide-name | fastfetch --file-raw -

```
i am using this for now
